version: "2.2"
services:
  dmadmin-namedindex:
    extends:
      file: "common.yml"
      service: "common"
    image: "registry.imanage.com/imanagelabs/reindex:1.3.166"
    container_name: "cr_pod-reindex-run-1"
    mem_limit: "512m"
    restart: on-failure:12
    environment:
     - "--pod_name"
     - "einstein"
    #  - "--only_for_newest_index"
