version: "2.2"
services:
  common-no-tmpfs:
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    network_mode: "public"
    environment:
      DISCOVERY_HOST: "${DISCOVERY_HOST}"
      HOST: "${DISCOVERY_HOST}"
      TASK_HOST: "${DISCOVERY_HOST}"
      ZK_CONNECT: "${DISCOVERY_HOST}:2181"
      ARCHIVE_LIST_USER: "event-processor-pipeline-service@operations.com"
      ARCHIVE_LIST_PASSWORD: "event-processor-pipeline-service"
      SMTP_WEB_USER: "event-processor-pipeline-service@operations.com"
      SMTP_WEB_PASSWORD: "event-processor-pipeline-service"
      SWIFT_TEMPSTORE_USERNAME: "tempstore:system"
      SWIFT_TEMPSTORE_PASSWORD: "tempstore_system_password"
      MA_SERVICE_PORT_REDIS: "6379"
      MA_SERVICE_PORT_CASSANDRA_INTER: "7000"
      MA_SERVICE_PORT_MAMTA_SMTPS: "465"
      MA_SERVICE_PORT_STORM_UI: "18080"
      MA_SERVICE_PORT_ELASTICSEARCH2: "9950"
      MA_SERVICE_PORT_KAFKA: "10001"
      MA_SERVICE_PORT_CASSANDRA_THRIFT_CLIENT: "9160"
      MA_SERVICE_PORT_PRIZM_APP_SERVER: "3000"
      MA_SERVICE_PORT_GRAPHITE: "28080"
      MA_SERVICE_PORT_WEB: "9000"
      MA_SERVICE_PORT_MAMTA_SMTP: "25"
      MA_SERVICE_PORT_FRONTEND_HTTP: "80"
      MA_SERVICE_PORT_KAFKA_MONITOR: "4950"
      MA_SERVICE_PORT_GRAFANA: "3002"
      MA_SERVICE_PORT_EVENT_ACCEPTANCE: "5002"
      MA_SERVICE_PORT_SPARK_MASTER: "7078"
      MA_SERVICE_PORT_ELASTICSEARCH: "9200"
      MA_SERVICE_PORT_FRONTEND_HTTPS: "443"
      MA_SERVICE_PORT_MARIADB: "3306"
      MA_SERVICE_PORT_SPARK_MASTER_WEB_UI: "8081"
      MA_SERVICE_PORT_ZOOKEEPER_CLIENT: "2181"
      MA_SERVICE_PORT_SPARK_JOBSERVER: "8090"
      MA_SERVICE_PORT_SPARK_WORKER_WEB_UI: "8082"
      MA_SERVICE_PORT_SPARK_MASTER_WINDOWS_WEB_UI: "8083"
      MA_SERVICE_PORT_PRIZM_SERVER: "18681"
      MA_SERVICE_PORT_STORM_NIMBUS: "6627"
      MA_SERVICE_PORT_MAMTA_MESSAGE: "587"
      MA_SERVICE_PORT_SINGULARITY: "7099"
      MA_SERVICE_PORT_CASSANDRA_OPSCENTER_STOMP: "61620"
      MA_SERVICE_PORT_SOLR: "8983"
      MA_SERVICE_PORT_SPARK_MASTER_WINDOWS: "7079"
      MA_SERVICE_PORT_CASSANDRA_THRIFT_INTER: "7001"
      MA_SERVICE_PORT_ELASTICSEARCH_MONITOR: "9850"
      MA_SERVICE_PORT_LANGUAGE_DETECTOR: "8084"
      MA_SERVICE_PORT_CASSANDRA_CLIENT: "9042"
      MA_SERVICE_PORT_ELASTICSEARCH_TRANSPORT: "9300"
      MA_SERVICE_PORT_CASSANDRA_JMX: "7199"
      MA_SERVICE_PORT_EXTRACTION: "8086"

  common:
    extends:
      service: "common-no-tmpfs"
    tmpfs:
      - /var/lib
