version: "2.2"
services:
  extraction-service:
    extends:
      file: "common.yml"
      service: "common"
    image: "m-extraction:latest"
    mem_limit: "1024m"
    restart: on-failure:3
    scale: 3
    environment:
      OCR_ENABLED: "false"
      SERVICE_LOG_LEVEL: "INFO"
      
