version: "2.2"
services:
  dmadmin-namedindex:
    extends:
      file: "common.yml"
      service: "common"
    image: "m-extraction:latest"
    container_name: "cr_m-extraction-run-1"
    mem_limit: "1024m"
    restart: on-failure:3
    environment:
      OCR_ENABLED: "false"
      SERVICE_LOG_LEVEL: "TRACE"
      
