version: "2.2"
services:
  elasticsearchuvmaster3: &esu-master-config
    extends:
      file: "common.yml"
      service: "common"
    image: "elasticsearch7:latest"
    mem_limit: "1536m"
    restart: on-failure:12
    environment:
      RACK_ID: "rack3"
      SERVER_ID: "ganges"
      DISK_ID: "disk301"
      NODE_NAME: "master3"
      CLUSTER_NAME: "venus"
      ES_CLUSTER_NAME: venus-${DISCOVERY_HOST}
      ES_NETWORKING: "bridged"
      SERVICE_9900_NAME: "venus-elasticsearchtransport"
      SERVICE_9950_NAME: "venus-elasticsearch"
      NODE_TYPE: master_and_data
      DOCKER_FIX: '                                        '

  elasticsearchuvmaster2:
    <<: *esu-master-config
    environment:
      RACK_ID: "rack3"
      SERVER_ID: "nile"
      DISK_ID: "disk302"
      NODE_NAME: "master2"
      CLUSTER_NAME: "venus"
      ES_CLUSTER_NAME: venus-${DISCOVERY_HOST}
      ES_NETWORKING: "bridged"
      SERVICE_9900_NAME: "venus-elasticsearchtransport"
      SERVICE_9950_NAME: "venus-elasticsearch"
      NODE_TYPE: master_and_data
      DOCKER_FIX: '                                        '

  elasticsearchuvmaster1:
    <<: *esu-master-config
    ports:
      - "9950:9950"
    environment:
      RACK_ID: "rack3"
      SERVER_ID: "mississippi"
      DISK_ID: "disk303"
      NODE_NAME: "master1"
      CLUSTER_NAME: "venus"
      ES_CLUSTER_NAME: venus-${DISCOVERY_HOST}
      ES_NETWORKING: "bridged"
      SERVICE_9900_NAME: "venus-elasticsearchtransport"
      SERVICE_9950_NAME: "venus-elasticsearch"
      NODE_TYPE: master_and_data
      DOCKER_FIX: '                                        '
